# Generated by Django 4.2.16 on 2025-10-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrating',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
