# Generated by Django 4.2.16 on 2025-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_businessrating_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrating',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
