# Generated by Django 5.2.6 on 2025-10-10 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
            },
        ),
        migrations.RemoveField(
            model_name="business",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="business",
            name="views",
        ),
        migrations.AddField(
            model_name="business",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="business",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Total Views"),
        ),
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.TextField(default="", verbose_name="Address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_businesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
