# Generated by Django 5.2.6 on 2025-10-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_business_options_remove_business_rating_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Business", "verbose_name_plural": "Businesses"},
        ),
        migrations.RemoveField(
            model_name="business",
            name="description",
        ),
        migrations.RemoveField(
            model_name="business",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="business",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="total_views",
        ),
        migrations.AddField(
            model_name="business",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="Rating"),
        ),
        migrations.AddField(
            model_name="business",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="business",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_businesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
